### ISSUE TITLE
 How to register the CAME optimizer

### ISSUE THREAD

**Issue by xiechengmude** [yangluo7/CAME#1]
To replicate our result, first register the CAME optimizer to the transformer package. 

How to register the CAME optimizer to the transformer package. ?

Any tutorial? Thanks!

**Comment by yangluo7** [comment]
You can add CAME into https://github.com/huggingface/transformers/blob/main/src/transformers/optimization.py and use it following the similar way to AdamW that is the default optimizer in huggingface.
