### ISSUE TITLE
The in-place operation on 'update' seems to affect the 'exp_avg'. Is this behavior expected?

### ISSUE THREAD

**Issue by lzhqw** [yangluo7/CAME#2]
When the parameter is a vector, the in-place operation of the variable `update` seems to affect the value of the variable `exp_avg`. Is this behavior expected?

In this code segment, when not factored, `update` is first assigned to `exp_avg` and then multiplied by lr, which results in `exp_avg` also being multiplied by lr.

```python
if factored:
    exp_avg_res_row = state["exp_avg_res_row"]
    exp_avg_res_col = state["exp_avg_res_col"]

    exp_avg_res_row.mul_(group["betas"][2]).add_(
        res.mean(dim=-1), alpha=1.0 - group["betas"][2]
    )
    exp_avg_res_col.mul_(group["betas"][2]).add_(
        res.mean(dim=-2), alpha=1.0 - group["betas"][2]
    )

    # Approximation of exponential moving average of instability
    res_approx = self._approx_sq_grad(exp_avg_res_row, exp_avg_res_col)
    update = res_approx.mul_(exp_avg)
else:
    update = exp_avg
if group["weight_decay"] != 0:
    p.data.add_(
            p.data, alpha=-group["weight_decay"] * group["lr"]
        )

update.mul_(group["lr"])
p.data.add_(-update)
```

When use `update = exp_avg.clone()`， the rate of convergence is faster.
Here is a test on rosenbrock function:
![Figure_1](https://github.com/yangluo7/CAME/assets/98437112/2adf8a1e-dad1-48d3-a33c-48ed3784559a)

**Comment by yangluo7** [comment]
Thanks for pointing it out! Yes, we fixed this error in the final implementation but uploaded an older version. Actually, we didn't find a significant difference between the two versions when training GPT models, but we still recommend using the modified version.

**Comment by lishuai-97** [comment]
Hi @lzhqw, your rosenbrock function example is so clear! Would you please share the scripts to produce the results of the toy examples and to generate the gif files? Thanks!

**Comment by lzhqw** [comment]
> Hi @lzhqw, your rosenbrock function example is so clear! Would you please share the scripts to produce the results of the toy examples and to generate the gif files? Thanks!

I referred to the video https://www.youtube.com/watch?v=zvp8K4iX2Cs
```python
import numpy as np
import torch
from Came import CAME, CAME_Fix
import matplotlib.pyplot as plt


def f(xy):
    x, y = xy
    return (1 - x) ** 2 + 100 * (y - x ** 2) ** 2


def run_optimizer(xy_init, optimizer_class, n_iter, **optimizer_kwargs):
    xy_t = torch.tensor(xy_init, requires_grad=True)
    optimizer = optimizer_class([xy_t], **optimizer_kwargs)

    path = np.empty((n_iter + 1, 2))
    path[0, :] = xy_init
    for i in range(1, n_iter + 1):
        optimizer.zero_grad()
        loss = f(xy_t)
        loss.backward()
        optimizer.step()
        path[i, :] = xy_t.detach().numpy()
    return path


def create_trace(names, paths):
    x = np.linspace(-0.5, 2, 300)
    y = np.linspace(0.5, 3, 300)
    x, y = np.meshgrid(x, y)
    z = f([x, y])

    plt.figure(figsize=(8, 6))
    contour = plt.contour(x, y, z, colors='black')
    plt.clabel(contour, inline=True, fontsize=8)
    plt.imshow(z, extent=[-0.5, 2, 0.5, 3], origin='lower', cmap='RdBu_r', alpha=0.5)
    plt.colorbar()
    minimum = (1.0, 1.0)

    for i, path in enumerate(paths):
        plt.plot(path[::10, 0], path[::10, 1], label=names[i])
        plt.scatter(path[::10, 0], path[::10, 1])
    plt.plot(*minimum, "rD")
    plt.xlabel('x')
    plt.ylabel('y')
    plt.legend()
    plt.show()


xy_init = (0.0, 2.5)
path1 = run_optimizer(xy_init=xy_init,
                      optimizer_class=CAME,
                      n_iter=1500,
                      lr=0.1,
                      eps=(1e-30, 1e-16),
                      clip_threshold=1.0,
                      betas=(0.9, 0.999, 0.9999),
                      weight_decay=0.0,
                      )
path2 = run_optimizer(xy_init=xy_init,
                      optimizer_class=CAME_Fix,
                      n_iter=1500,
                      lr=0.1,
                      eps=(1e-30, 1e-16),
                      clip_threshold=1.0,
                      betas=(0.9, 0.999, 0.9999),
                      weight_decay=0.0,
                      )
create_trace(["Came", "Came_use_clone"], [path1, path2])
```

**Comment by lishuai-97** [comment]
> > Hi @lzhqw, your rosenbrock function example is so clear! Would you please share the scripts to produce the results of the toy examples and to generate the gif files? Thanks!
> 
> I referred to the video https://www.youtube.com/watch?v=zvp8K4iX2Cs
> 
> ```python
> import numpy as np
> import torch
> from Came import CAME, CAME_Fix
> import matplotlib.pyplot as plt
> 
> 
> def f(xy):
>     x, y = xy
>     return (1 - x) ** 2 + 100 * (y - x ** 2) ** 2
> 
> 
> def run_optimizer(xy_init, optimizer_class, n_iter, **optimizer_kwargs):
>     xy_t = torch.tensor(xy_init, requires_grad=True)
>     optimizer = optimizer_class([xy_t], **optimizer_kwargs)
> 
>     path = np.empty((n_iter + 1, 2))
>     path[0, :] = xy_init
>     for i in range(1, n_iter + 1):
>         optimizer.zero_grad()
>         loss = f(xy_t)
>         loss.backward()
>         optimizer.step()
>         path[i, :] = xy_t.detach().numpy()
>     return path
> 
> 
> def create_trace(names, paths):
>     x = np.linspace(-0.5, 2, 300)
>     y = np.linspace(0.5, 3, 300)
>     x, y = np.meshgrid(x, y)
>     z = f([x, y])
> 
>     plt.figure(figsize=(8, 6))
>     contour = plt.contour(x, y, z, colors='black')
>     plt.clabel(contour, inline=True, fontsize=8)
>     plt.imshow(z, extent=[-0.5, 2, 0.5, 3], origin='lower', cmap='RdBu_r', alpha=0.5)
>     plt.colorbar()
>     minimum = (1.0, 1.0)
> 
>     for i, path in enumerate(paths):
>         plt.plot(path[::10, 0], path[::10, 1], label=names[i])
>         plt.scatter(path[::10, 0], path[::10, 1])
>     plt.plot(*minimum, "rD")
>     plt.xlabel('x')
>     plt.ylabel('y')
>     plt.legend()
>     plt.show()
> 
> 
> xy_init = (0.0, 2.5)
> path1 = run_optimizer(xy_init=xy_init,
>                       optimizer_class=CAME,
>                       n_iter=1500,
>                       lr=0.1,
>                       eps=(1e-30, 1e-16),
>                       clip_threshold=1.0,
>                       betas=(0.9, 0.999, 0.9999),
>                       weight_decay=0.0,
>                       )
> path2 = run_optimizer(xy_init=xy_init,
>                       optimizer_class=CAME_Fix,
>                       n_iter=1500,
>                       lr=0.1,
>                       eps=(1e-30, 1e-16),
>                       clip_threshold=1.0,
>                       betas=(0.9, 0.999, 0.9999),
>                       weight_decay=0.0,
>                       )
> create_trace(["Came", "Came_use_clone"], [path1, path2])
> ```

Thank you very much for your reply, which is very helpful to me！
