### ISSUE TITLE
Question regarding performance with repeats

### ISSUE THREAD

**Issue by kukaiN** [yangluo7/CAME#4]
Hi, amazing paper.

I was wondering if you tested or have any knowledge of CAME working with LR schedulers that utilizes repeats like Cosine with repeats, Cosine with Annealing?  Is it better to have a constant or a simple decaying LR scheduler over the repeating methods?

**Comment by yangluo7** [comment]
That's an intriguing question about CAME. Unfortunately, I haven't experimentally tested CAME LR schedulers that utilize repeats. Please feel free to share any insights you may have if you've looked into this area.
